/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.apache.dubbo.rpc.protocol.grpc.support;

public final class HelloWorldProto {
    private HelloWorldProto() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_helloworld_HelloRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_helloworld_HelloRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_helloworld_HelloReply_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_helloworld_HelloReply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        String[] descriptorData = {
            "\n\020helloworld.proto\022\nhelloworld\"\034\n\014HelloR" +
                "equest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007me" +
                "ssage\030\001 \001(\tB6\n\033org.apache.dubbo.demo.hel" +
                "loB\017HelloWorldProtoP\001\242\002\003HLWb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                }, assigner);
        internal_static_helloworld_HelloRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_helloworld_HelloRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_helloworld_HelloRequest_descriptor,
            new String[] {"Name",});
        internal_static_helloworld_HelloReply_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_helloworld_HelloReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_helloworld_HelloReply_descriptor,
            new String[] {"Message",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
