/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.alibaba.dubbo.demo;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AvroService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroService\",\"namespace\":\"com.alibaba.dubbo.demo\",\"types\":[],\"messages\":{\"sayHello\":{\"request\":[{\"name\":\"id\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  /**
   */
  CharSequence sayHello(CharSequence id) throws org.apache.avro.AvroRemoteException;

}