{
 "title": "benchmark",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Throughput (常见框架对比)",
   "type": "timeseries",
   "description": "1",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'grpc' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND name = 'grpc' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'spring-cloud' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'spring-cloud' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "Throughput (各协议对比)",
   "type": "timeseries",
   "description": "1",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'triple' FROM benchmark.benchmark_score WHERE ( benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND name = 'triple-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-fastjson2' FROM benchmark.benchmark_score WHERE ( benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'grpc' FROM benchmark.benchmark_score WHERE ( benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND name = 'grpc' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'rest(spring-cloud)' FROM benchmark.benchmark_score WHERE ( benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'spring-cloud' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "Throughput (序列化对比)",
   "type": "timeseries",
   "description": "1",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-fastjson2' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND  name = 'dubbo-fastjson2-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-hessianlite' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND  name = 'dubbo-hessianlite-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'triple-pb' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND  name = 'triple-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-pb' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND  name = 'dubbo-pb-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-kryo' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-kryo-3.2' AND mode = 'thrpt') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "AverageTime (常见框架对比)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'grpc' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND name = 'grpc' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'spring-cloud' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'spring-cloud' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "AverageTime (各协议对比)",
   "type": "timeseries",
   "description": "1",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'triple' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND name = 'triple-3.2' AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND name = 'dubbo-fastjson2-3.2' AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'grpc' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND name = 'grpc' AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'rest(spring-cloud)' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND name = 'spring-cloud' AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "AverageTime (序列化对比)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'triple-pb' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND name = 'triple-3.2' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-fastjson2' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-hessianlite' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-hessianlite-3.2' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-pb' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND name = 'dubbo-pb-3.2' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), score AS 'dubbo-kryo' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-kryo-3.2' AND mode = 'avgt') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "Dubbo Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p99 AS 'p99' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p95 AS 'p95' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p90 AS 'p90' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'dubbo-fastjson2-3.2' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "Triple Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 39 },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p99 AS 'p99' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND name = 'triple-3.2' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p95 AS 'p95' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND name = 'triple-3.2' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p90 AS 'p90' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientPb.createUser' AND name = 'triple-3.2' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "gRPC Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p99 AS 'p99' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND name = 'grpc' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p95 AS 'p95' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND name = 'grpc' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p90 AS 'p90' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientNativeGrpc.createUser' AND name = 'grpc' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    }
   ]
  },
  {
   "title": "SpringCloud Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p99 AS 'p99' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'spring-cloud' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p95 AS 'p95' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'spring-cloud' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    },
    {
     "dataset": "benchmark",
     "rawSql": "SELECT CONVERT_TZ(benchmark_time, '+08:00', '+00:00'), p90 AS 'p90' FROM benchmark.benchmark_score WHERE (benchmark_time >= $__timeFrom() AND benchmark_time <= $__timeTo() AND method = 'org.apache.dubbo.benchmark.ClientSimple.createUser' AND name = 'spring-cloud' AND mode = 'sample') order by benchmark_time asc LIMIT 1000"
    }
   ]
  }
 ]
}