header:
  license:
    spdx-id: Apache-2.0
    content: |
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

  paths-ignore:
    - '**/*.versionsBackup'
    - '**/.idea/'
    - '**/*.iml'
    - '**/.settings/*'
    - '**/.classpath'
    - '**/.project'
    - '**/target/**'
    - '**/generated/**'
    - '**/*.log'
    - '**/codestyle/*'
    - '**/resources/META-INF/**'
    - '**/resources/mockito-extensions/**'
    - '**/*.proto'
    - '**/*.cache'
    - '**/*.txt'
    - '**/*.load'
    - '**/*.flex'
    - '**/*.fc'
    - '**/*.javascript'
    - '**/*.properties'
    - '**/*.sh'
    - '**/*.bat'
    - '**/*.md'
    - '**/*.svg'
    - '**/*.png'
    - '**/*.json'
    - '**/*.conf'
    - '**/*.ftl'
    - '**/*.tpl'
    - '**/*.factories'
    - '**/*.handlers'
    - '**/*.schemas'
    - '**/*.nojekyll'
    - '.git/'
    - '.github/**'
    - '**/.gitignore'
    - '**/.helmignore'
    - '.repository/'
    - 'compiler/**'
    - '.gitmodules'
    - '.mvn'
    - 'mvnw'
    - 'mvnw.cmd'
    - 'LICENSE'
    - 'NOTICE'
    - 'CNAME'
    - 'Jenkinsfile'
    - '**/vendor/**'
    - '**/src/test/resources/certs/**'
    - '**/src/test/resources/definition/**'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocal.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalMap.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/timer/Timeout.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/timer/Timer.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/timer/TimerTask.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/utils/CIDRUtils.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/utils/Utf8Utils.java'
    - 'dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/EmbeddedZooKeeper.java'
    - 'dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/utils/TestSocketUtils.java'
    - 'dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java'
    - 'dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/rest/cors/CorsHeaderFilter.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/serial/SerializingExecutor.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/AbstractAotMojo.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/AbstractDependencyFilterMojo.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/CommandLineBuilder.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/DependencyFilter.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/Exclude.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/ExcludeFilter.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/FilterableDependency.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/Include.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/IncludeFilter.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/JavaCompilerPluginConfiguration.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/JavaExecutable.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/JavaProcessExecutor.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/MatchingGroupIdFilter.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/RunArguments.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/aot/RunProcess.java'
    - 'dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/generate/BasicJsonWriter.java'
    - 'dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/api/ExecutableMode.java'
    - 'dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/api/MemberCategory.java'
    - 'dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/DubboMergingDigest.java'
    - 'dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/DubboAbstractTDigest.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/logger/helpers/FormattingTuple.java'
    - 'dubbo-common/src/main/java/org/apache/dubbo/common/logger/helpers/MessageFormatter.java'
    - 'dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/protoc/DubboProtocCompilerMojo.java'
    - 'dubbo-plugin/dubbo-compiler/src/main/java/org/apache/dubbo/gen/utils/ProtoTypeMap.java'

  comment: on-failure

  license-location-threshold: 130

dependency:
  files:
    - pom.xml
    - dubbo-dependencies-bom/pom.xml
  licenses:
    - name: com.fasterxml.jackson.core:jackson-annotations
      license: Apache-2.0
    - name: com.fasterxml.jackson.core:jackson-core
      license: Apache-2.0
    - name: com.fasterxml.jackson.core:jackson-databind
      license: Apache-2.0
    - name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
      license: Apache-2.0
    - name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
      license: Apache-2.0
    - name: com.google.code.gson:gson
      license: Apache-2.0
    - name: com.google.guava:listenablefuture
      license: Apache-2.0
    - name: com.salesforce.servicelibs:grpc-contrib
      license: BSD 3-clause
    - name: com.squareup.okhttp3:logging-interceptor
      license: Apache-2.0
    - name: com.squareup.okhttp3:okhttp
      license: Apache-2.0
    - name: com.squareup.okio:okio
      license: Apache-2.0
    - name: com.sun.xml.fastinfoset:FastInfoset
      license: Apache-2.0
    - name: io.envoyproxy.controlplane:api
      license: Apache-2.0
    - name: io.swagger:swagger-annotations
      license: Apache-2.0
    - name: io.swagger:swagger-models
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-actuator
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-autoconfigure
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-configuration-processor
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-starter
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-starter-actuator
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-starter-logging
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-starter-tomcat
      license: Apache-2.0
    - name: org.springframework.boot:spring-boot-starter-web
      license: Apache-2.0
    - name: org.slf4j:slf4j-api
      license: MIT
    - name: org.slf4j:slf4j-log4j12
      license: MIT
    - name: org.jboss.resteasy:resteasy-jaxrs
      license: Apache-2.0
    - name: org.jboss.resteasy:resteasy-client
      license: Apache-2.0
    - name: org.jboss.resteasy:resteasy-netty4
      license: Apache-2.0
    - name: org.jboss.resteasy:resteasy-jdk-http
      license: Apache-2.0
    - name: org.jboss.resteasy:resteasy-jackson-provider
      license: Apache-2.0
    - name: org.jboss.resteasy:resteasy-jaxb-provider
      license: Apache-2.0
    - name: net.jcip:jcip-annotations
      license: Apache-2.0
    - name: org.apache.zookeeper:zookeeper
      license: Apache-2.0
    - name: org.apache.zookeeper:zookeeper-jute
      license: Apache-2.0
    - name: net.bytebuddy:byte-buddy
      license: Apache-2.0
    - name: javax.enterprise:cdi-api
      license: Apache-2.0
    - name: org.codehaus.plexus:plexus-component-annotations
      license: Apache-2.0
    - name: org.slf4j:jcl-over-slf4j
      license: Apache-2.0
    - name: org.slf4j:jul-to-slf4j
      license: Apache-2.0
    - name: org.codehaus.plexus:plexus-interpolation
      license: Apache-2.0
    - name: org.sonatype.plexus:plexus-sec-dispatcher
      license: Apache-2.0
    - name: org.sonatype.plexus:plexus-cipher
      license: Apache-2.0
    - name: com.alibaba.csp:sentinel-apache-dubbo3-adapter
      license: Apache-2.0
    - name: com.alibaba.csp:sentinel-transport-simple-http
      license: Apache-2.0
    - name: com.alibaba.csp:sentinel-transport-common
      license: Apache-2.0
    - name: com.alibaba.csp:sentinel-datasource-extension
      license: Apache-2.0
    - name: com.alibaba.csp:sentinel-core
      license: Apache-2.0
    - name: com.google.protobuf:protobuf-java
      license: BSD 3-clause
    - name: com.google.protobuf:protobuf-java-util
      license: BSD 3-clause
    - name: org.antlr:antlr4
      license: BSD 3-clause
    - name: org.antlr:antlr-runtime
      license: BSD 3-clause
    - name: org.antlr:ST4
      license: BSD 3-clause
    # multi license
    - name: org.javassist:javassist
      license: Apache-2.0
    - name: javax.annotation:javax.annotation-api
      license: CDDL-1.0
    - name: com.salesforce.servicelibs:jprotoc
      license: CDDL-1.0
    - name: org.checkerframework:checker-compat-qual
      license: MIT
    - name: ch.qos.logback:logback-classic
      license: EPL-1.0
    - name: ch.qos.logback:logback-core
      license: EPL-1.0
    - name: javax.servlet:javax.servlet-api
      license: CDDL-1.1
    - name: com.sun.activation:javax.activation
      license: CDDL-1.1
    - name: javax.activation:activation
      license: CDDL-1.1
    - name: jakarta.annotation:jakarta.annotation-api
      license: EPL-2.0
    - name: org.glassfish:jakarta.el
      license: EPL-2.0
    - name: org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec
      license: CDDL-1.1
    - name: org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec
      license: EPL-2.0
    - name: org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec
      license: EPL-2.0
  excludes:
    - name: javax.xml.bind:jsr173_api
