// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.apache.dubbo.rpc.protocol.tri.proto;

public final class DemoServiceProto {
  private DemoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rservice.proto\"\034\n\014HelloRequest\022\014\n\004name\030" +
      "\001 \001(\t\" \n\rHelloResponse\022\017\n\007message\030\001 \001(\t2" +
      "\330\001\n\013DemoService\022+\n\nhelloUnary\022\r.HelloReq" +
      "uest\032\016.HelloResponse\0224\n\021helloClientStrea" +
      "m\022\r.HelloRequest\032\016.HelloResponse(\001\0224\n\021he" +
      "lloServerStream\022\r.HelloRequest\032\016.HelloRe" +
      "sponse0\001\0220\n\rhelloBIStream\022\r.HelloRequest" +
      "\032\016.HelloResponse0\001B=\n\'org.apache.dubbo.r" +
      "pc.protocol.tri.protoB\020DemoServiceProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
