// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Echo.proto

package com.alibaba.dubbo.rpc.protocol.protobuf.proto;

public final class EchoProto {
  private EchoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EchoRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 data = 1;
    /**
     * <code>required int32 data = 1;</code>
     */
    boolean hasData();
    /**
     * <code>required int32 data = 1;</code>
     */
    int getData();
  }
  /**
   * Protobuf type {@code EchoRequest}
   */
  public static final class EchoRequest extends
      com.google.protobuf.GeneratedMessage
      implements EchoRequestOrBuilder {
    // Use EchoRequest.newBuilder() to construct.
    private EchoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EchoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EchoRequest defaultInstance;
    public static EchoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public EchoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EchoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              data_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.class, com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<EchoRequest> PARSER =
        new com.google.protobuf.AbstractParser<EchoRequest>() {
      public EchoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EchoRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EchoRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private int data_;
    /**
     * <code>required int32 data = 1;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 data = 1;</code>
     */
    public int getData() {
      return data_;
    }

    private void initFields() {
      data_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EchoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.class, com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.Builder.class);
      }

      // Construct using com.alibaba.dubbo.rpc.protocol.protobuf.EchoProto.EchoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoRequest_descriptor;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest getDefaultInstanceForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.getDefaultInstance();
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest build() {
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest buildPartial() {
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest result = new com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest) {
          return mergeFrom((com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest other) {
        if (other == com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 data = 1;
      private int data_ ;
      /**
       * <code>required int32 data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 data = 1;</code>
       */
      public int getData() {
        return data_;
      }
      /**
       * <code>required int32 data = 1;</code>
       */
      public Builder setData(int value) {
        bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 data = 1;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EchoRequest)
    }

    static {
      defaultInstance = new EchoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EchoRequest)
  }

  public interface EchoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code EchoResponse}
   */
  public static final class EchoResponse extends
      com.google.protobuf.GeneratedMessage
      implements EchoResponseOrBuilder {
    // Use EchoResponse.newBuilder() to construct.
    private EchoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EchoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EchoResponse defaultInstance;
    public static EchoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public EchoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EchoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.class, com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<EchoResponse> PARSER =
        new com.google.protobuf.AbstractParser<EchoResponse>() {
      public EchoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EchoResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EchoResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EchoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.class, com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.Builder.class);
      }

      // Construct using com.alibaba.dubbo.rpc.protocol.protobuf.EchoProto.EchoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.internal_static_EchoResponse_descriptor;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse getDefaultInstanceForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance();
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse build() {
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse buildPartial() {
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse result = new com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse) {
          return mergeFrom((com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse other) {
        if (other == com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EchoResponse)
    }

    static {
      defaultInstance = new EchoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EchoResponse)
  }

  /**
   * Protobuf service {@code EchoService}
   */
  public static abstract class EchoService
      implements com.google.protobuf.Service {
    protected EchoService() {}

    public interface Interface {
      /**
       * <code>rpc Echo(.EchoRequest) returns (.EchoResponse);</code>
       */
      public abstract void echo(
          com.google.protobuf.RpcController controller,
          com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest request,
          com.google.protobuf.RpcCallback<com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new EchoService() {
        @java.lang.Override
        public  void echo(
            com.google.protobuf.RpcController controller,
            com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest request,
            com.google.protobuf.RpcCallback<com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse> done) {
          impl.echo(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.echo(controller, (com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Echo(.EchoRequest) returns (.EchoResponse);</code>
     */
    public abstract void echo(
        com.google.protobuf.RpcController controller,
        com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest request,
        com.google.protobuf.RpcCallback<com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.echo(controller, (com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest)request,
            com.google.protobuf.RpcUtil.<com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void echo(
          com.google.protobuf.RpcController controller,
          com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest request,
          com.google.protobuf.RpcCallback<com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.class,
            com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse echo(
          com.google.protobuf.RpcController controller,
          com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse echo(
          com.google.protobuf.RpcController controller,
          com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.alibaba.dubbo.rpc.protocol.protobuf.proto.EchoProto.EchoResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:EchoService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EchoRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/Echo.proto\"\033\n\013EchoRequest\022\014\n\004dat" +
      "a\030\001 \002(\005\"\036\n\014EchoResponse\022\016\n\006result\030\001 \002(\0052" +
      "2\n\013EchoService\022#\n\004Echo\022\014.EchoRequest\032\r.E" +
      "choResponseB7\n\'com.alibaba.dubbo.rpc.pro" +
      "tocol.protobufB\tEchoProto\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_EchoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_EchoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EchoRequest_descriptor,
              new java.lang.String[] { "Data", });
          internal_static_EchoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_EchoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EchoResponse_descriptor,
              new java.lang.String[] { "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
