licenses(["notice"])  # Apache 2

load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library_internal")

api_proto_library_internal(
    name = "previous_priorities",
    srcs = ["previous_priorities_config.proto"],
    deps = [
        "//envoy/api/v2/core:base",
    ],
)
