// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.alibaba.dubbo.rpc.protocol.protobuf;

public final class ProtobufMessage {
  private ProtobufMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code PackageType}
   */
  public enum PackageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTBEAT = 0;</code>
     */
    HEARTBEAT(0, 0),
    /**
     * <code>REQUEST = 1;</code>
     */
    REQUEST(1, 1),
    /**
     * <code>RESPONSE = 2;</code>
     */
    RESPONSE(2, 2),
    /**
     * <code>PUSH = 3;</code>
     */
    PUSH(3, 3),
    /**
     * <code>ERROR = 4;</code>
     */
    ERROR(4, 4),
    ;

    /**
     * <code>HEARTBEAT = 0;</code>
     */
    public static final int HEARTBEAT_VALUE = 0;
    /**
     * <code>REQUEST = 1;</code>
     */
    public static final int REQUEST_VALUE = 1;
    /**
     * <code>RESPONSE = 2;</code>
     */
    public static final int RESPONSE_VALUE = 2;
    /**
     * <code>PUSH = 3;</code>
     */
    public static final int PUSH_VALUE = 3;
    /**
     * <code>ERROR = 4;</code>
     */
    public static final int ERROR_VALUE = 4;


    public final int getNumber() { return value; }

    public static PackageType valueOf(int value) {
      switch (value) {
        case 0: return HEARTBEAT;
        case 1: return REQUEST;
        case 2: return RESPONSE;
        case 3: return PUSH;
        case 4: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PackageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PackageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PackageType>() {
            public PackageType findValueByNumber(int number) {
              return PackageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final PackageType[] VALUES = values();

    public static PackageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PackageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PackageType)
  }

  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Heartbeat)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Heartbeat}
   */
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Heartbeat)
      HeartbeatOrBuilder {
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Heartbeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Heartbeat defaultInstance;
    public static Heartbeat getDefaultInstance() {
      return defaultInstance;
    }

    public Heartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Heartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Heartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.Builder.class);
    }

    public static com.google.protobuf.Parser<Heartbeat> PARSER =
        new com.google.protobuf.AbstractParser<Heartbeat>() {
      public Heartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Heartbeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Heartbeat> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Heartbeat)
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Heartbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.Builder.class);
      }

      // Construct using com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Heartbeat_descriptor;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat getDefaultInstanceForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.getDefaultInstance();
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat build() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat buildPartial() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat result = new com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat) {
          return mergeFrom((com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat other) {
        if (other == com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Heartbeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Heartbeat)
    }

    static {
      defaultInstance = new Heartbeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Heartbeat)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 identify = 1;</code>
     */
    boolean hasIdentify();
    /**
     * <code>optional uint64 identify = 1;</code>
     */
    long getIdentify();

    /**
     * <code>optional string method = 2;</code>
     */
    boolean hasMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>optional string service = 3;</code>
     */
    boolean hasService();
    /**
     * <code>optional string service = 3;</code>
     */
    java.lang.String getService();
    /**
     * <code>optional string service = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    /**
     * <code>optional bytes request = 4;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional bytes request = 4;</code>
     */
    com.google.protobuf.ByteString getRequest();
  }
  /**
   * Protobuf type {@code Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              identify_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              method_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              service_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              request_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IDENTIFY_FIELD_NUMBER = 1;
    private long identify_;
    /**
     * <code>optional uint64 identify = 1;</code>
     */
    public boolean hasIdentify() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 identify = 1;</code>
     */
    public long getIdentify() {
      return identify_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 2;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_FIELD_NUMBER = 3;
    private java.lang.Object service_;
    /**
     * <code>optional string service = 3;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string service = 3;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          service_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString request_;
    /**
     * <code>optional bytes request = 4;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes request = 4;</code>
     */
    public com.google.protobuf.ByteString getRequest() {
      return request_;
    }

    private void initFields() {
      identify_ = 0L;
      method_ = "";
      service_ = "";
      request_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, identify_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServiceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, request_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, identify_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServiceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, request_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.Builder.class);
      }

      // Construct using com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        identify_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        service_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        request_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Request_descriptor;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request getDefaultInstanceForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.getDefaultInstance();
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request build() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request buildPartial() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request result = new com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identify_ = identify_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.request_ = request_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request) {
          return mergeFrom((com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request other) {
        if (other == com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request.getDefaultInstance()) return this;
        if (other.hasIdentify()) {
          setIdentify(other.getIdentify());
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000002;
          method_ = other.method_;
          onChanged();
        }
        if (other.hasService()) {
          bitField0_ |= 0x00000004;
          service_ = other.service_;
          onChanged();
        }
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long identify_ ;
      /**
       * <code>optional uint64 identify = 1;</code>
       */
      public boolean hasIdentify() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 identify = 1;</code>
       */
      public long getIdentify() {
        return identify_;
      }
      /**
       * <code>optional uint64 identify = 1;</code>
       */
      public Builder setIdentify(long value) {
        bitField0_ |= 0x00000001;
        identify_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 identify = 1;</code>
       */
      public Builder clearIdentify() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identify_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 2;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object service_ = "";
      /**
       * <code>optional string service = 3;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public java.lang.String getService() {
        java.lang.Object ref = service_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            service_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        java.lang.Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public Builder setService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000004);
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString request_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes request = 4;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes request = 4;</code>
       */
      public com.google.protobuf.ByteString getRequest() {
        return request_;
      }
      /**
       * <code>optional bytes request = 4;</code>
       */
      public Builder setRequest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        request_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes request = 4;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Request)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional uint32 result = 1;</code>
     */
    int getResult();

    /**
     * <code>optional bytes response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional bytes response = 2;</code>
     */
    com.google.protobuf.ByteString getResponse();
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              response_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional uint32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString response_;
    /**
     * <code>optional bytes response = 2;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes response = 2;</code>
     */
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    private void initFields() {
      result_ = 0;
      response_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.Builder.class);
      }

      // Construct using com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_Response_descriptor;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response getDefaultInstanceForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.getDefaultInstance();
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response build() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response buildPartial() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response result = new com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.response_ = response_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response) {
          return mergeFrom((com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response other) {
        if (other == com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>optional uint32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional uint32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 2;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes response = 2;</code>
       */
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 2;</code>
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 2;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Response)
  }

  public interface RpcMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .PackageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .PackageType type = 1;</code>
     */
    com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType getType();

    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>optional uint64 identify = 3;</code>
     */
    boolean hasIdentify();
    /**
     * <code>optional uint64 identify = 3;</code>
     */
    long getIdentify();

    /**
     * <code>optional bytes serialized = 4;</code>
     */
    boolean hasSerialized();
    /**
     * <code>optional bytes serialized = 4;</code>
     */
    com.google.protobuf.ByteString getSerialized();
  }
  /**
   * Protobuf type {@code RpcMessage}
   */
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RpcMessage)
      RpcMessageOrBuilder {
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMessage defaultInstance;
    public static RpcMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType value = com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              identify_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              serialized_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_RpcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_RpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMessage> PARSER =
        new com.google.protobuf.AbstractParser<RpcMessage>() {
      public RpcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType type_;
    /**
     * <code>optional .PackageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PackageType type = 1;</code>
     */
    public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType getType() {
      return type_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IDENTIFY_FIELD_NUMBER = 3;
    private long identify_;
    /**
     * <code>optional uint64 identify = 3;</code>
     */
    public boolean hasIdentify() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 identify = 3;</code>
     */
    public long getIdentify() {
      return identify_;
    }

    public static final int SERIALIZED_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString serialized_;
    /**
     * <code>optional bytes serialized = 4;</code>
     */
    public boolean hasSerialized() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes serialized = 4;</code>
     */
    public com.google.protobuf.ByteString getSerialized() {
      return serialized_;
    }

    private void initFields() {
      type_ = com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType.HEARTBEAT;
      timestamp_ = 0L;
      identify_ = 0L;
      serialized_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, identify_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, serialized_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, identify_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, serialized_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcMessage)
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_RpcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_RpcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.class, com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.Builder.class);
      }

      // Construct using com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType.HEARTBEAT;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        identify_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        serialized_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.internal_static_RpcMessage_descriptor;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage getDefaultInstanceForType() {
        return com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.getDefaultInstance();
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage build() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage buildPartial() {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage result = new com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.identify_ = identify_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serialized_ = serialized_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage) {
          return mergeFrom((com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage other) {
        if (other == com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIdentify()) {
          setIdentify(other.getIdentify());
        }
        if (other.hasSerialized()) {
          setSerialized(other.getSerialized());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.RpcMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType type_ = com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType.HEARTBEAT;
      /**
       * <code>optional .PackageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PackageType type = 1;</code>
       */
      public com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType getType() {
        return type_;
      }
      /**
       * <code>optional .PackageType type = 1;</code>
       */
      public Builder setType(com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .PackageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.alibaba.dubbo.rpc.protocol.protobuf.ProtobufMessage.PackageType.HEARTBEAT;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long identify_ ;
      /**
       * <code>optional uint64 identify = 3;</code>
       */
      public boolean hasIdentify() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 identify = 3;</code>
       */
      public long getIdentify() {
        return identify_;
      }
      /**
       * <code>optional uint64 identify = 3;</code>
       */
      public Builder setIdentify(long value) {
        bitField0_ |= 0x00000004;
        identify_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 identify = 3;</code>
       */
      public Builder clearIdentify() {
        bitField0_ = (bitField0_ & ~0x00000004);
        identify_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString serialized_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes serialized = 4;</code>
       */
      public boolean hasSerialized() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes serialized = 4;</code>
       */
      public com.google.protobuf.ByteString getSerialized() {
        return serialized_;
      }
      /**
       * <code>optional bytes serialized = 4;</code>
       */
      public Builder setSerialized(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serialized_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes serialized = 4;</code>
       */
      public Builder clearSerialized() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serialized_ = getDefaultInstance().getSerialized();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RpcMessage)
    }

    static {
      defaultInstance = new RpcMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RpcMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Heartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Heartbeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\013\n\tHeartbeat\"M\n\007Request\022" +
      "\020\n\010identify\030\001 \001(\004\022\016\n\006method\030\002 \001(\t\022\017\n\007ser" +
      "vice\030\003 \001(\t\022\017\n\007request\030\004 \001(\014\",\n\010Response\022" +
      "\016\n\006result\030\001 \001(\r\022\020\n\010response\030\002 \001(\014\"a\n\nRpc" +
      "Message\022\032\n\004type\030\001 \001(\0162\014.PackageType\022\021\n\tt" +
      "imestamp\030\002 \001(\004\022\020\n\010identify\030\003 \001(\004\022\022\n\nseri" +
      "alized\030\004 \001(\014*L\n\013PackageType\022\r\n\tHEARTBEAT" +
      "\020\000\022\013\n\007REQUEST\020\001\022\014\n\010RESPONSE\020\002\022\010\n\004PUSH\020\003\022" +
      "\t\n\005ERROR\020\004B:\n\'com.alibaba.dubbo.rpc.prot" +
      "ocol.protobufB\017ProtobufMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Heartbeat_descriptor,
        new java.lang.String[] { });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Identify", "Method", "Service", "Request", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Result", "Response", });
    internal_static_RpcMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RpcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RpcMessage_descriptor,
        new java.lang.String[] { "Type", "Timestamp", "Identify", "Serialized", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
