/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePb.proto

package org.apache.dubbo.demo.protobuf.api;

public final class GooglePb {
  private GooglePb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GooglePBRequestTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.dubbo.demo.protobuf.api.GooglePBRequestType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string req = 1;</code>
     */
    String getReq();
    /**
     * <code>string req = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqBytes();
  }
  /**
   * Protobuf type {@code org.apache.dubbo.demo.protobuf.api.GooglePBRequestType}
   */
  public  static final class GooglePBRequestType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.apache.dubbo.demo.protobuf.api.GooglePBRequestType)
      GooglePBRequestTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GooglePBRequestType.newBuilder() to construct.
    private GooglePBRequestType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GooglePBRequestType() {
      req_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GooglePBRequestType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              req_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType.class, org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType.Builder.class);
    }

    public static final int REQ_FIELD_NUMBER = 1;
    private volatile Object req_;
    /**
     * <code>string req = 1;</code>
     */
    public String getReq() {
      Object ref = req_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        req_ = s;
        return s;
      }
    }
    /**
     * <code>string req = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqBytes() {
      Object ref = req_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        req_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, req_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, req_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType)) {
        return super.equals(obj);
      }
      org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType other = (org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType) obj;

      boolean result = true;
      result = result && getReq()
          .equals(other.getReq());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQ_FIELD_NUMBER;
      hash = (53 * hash) + getReq().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.dubbo.demo.protobuf.api.GooglePBRequestType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.dubbo.demo.protobuf.api.GooglePBRequestType)
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType.class, org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType.Builder.class);
      }

      // Construct using org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        req_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_descriptor;
      }

      public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType build() {
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType buildPartial() {
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType result = new org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType(this);
        result.req_ = req_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType) {
          return mergeFrom((org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getReq().isEmpty()) {
          req_ = other.req_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object req_ = "";
      /**
       * <code>string req = 1;</code>
       */
      public String getReq() {
        Object ref = req_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          req_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string req = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqBytes() {
        Object ref = req_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          req_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string req = 1;</code>
       */
      public Builder setReq(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        req_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string req = 1;</code>
       */
      public Builder clearReq() {

        req_ = getDefaultInstance().getReq();
        onChanged();
        return this;
      }
      /**
       * <code>string req = 1;</code>
       */
      public Builder setReqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        req_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.apache.dubbo.demo.protobuf.api.GooglePBRequestType)
    }

    // @@protoc_insertion_point(class_scope:org.apache.dubbo.demo.protobuf.api.GooglePBRequestType)
    private static final org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType();
    }

    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GooglePBRequestType>
        PARSER = new com.google.protobuf.AbstractParser<GooglePBRequestType>() {
      public GooglePBRequestType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GooglePBRequestType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GooglePBRequestType> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GooglePBRequestType> getParserForType() {
      return PARSER;
    }

    public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBRequestType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GooglePBResponseTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.dubbo.demo.protobuf.api.GooglePBResponseType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 1;</code>
     */
    String getResponse();
    /**
     * <code>string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code org.apache.dubbo.demo.protobuf.api.GooglePBResponseType}
   */
  public  static final class GooglePBResponseType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.apache.dubbo.demo.protobuf.api.GooglePBResponseType)
      GooglePBResponseTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GooglePBResponseType.newBuilder() to construct.
    private GooglePBResponseType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GooglePBResponseType() {
      response_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GooglePBResponseType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              response_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType.class, org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private volatile Object response_;
    /**
     * <code>string response = 1;</code>
     */
    public String getResponse() {
      Object ref = response_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      Object ref = response_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType)) {
        return super.equals(obj);
      }
      org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType other = (org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType) obj;

      boolean result = true;
      result = result && getResponse()
          .equals(other.getResponse());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.dubbo.demo.protobuf.api.GooglePBResponseType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.dubbo.demo.protobuf.api.GooglePBResponseType)
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType.class, org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType.Builder.class);
      }

      // Construct using org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        response_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_descriptor;
      }

      public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType build() {
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType buildPartial() {
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType result = new org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType(this);
        result.response_ = response_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType) {
          return mergeFrom((org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object response_ = "";
      /**
       * <code>string response = 1;</code>
       */
      public String getResponse() {
        Object ref = response_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder setResponse(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder clearResponse() {

        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        response_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.apache.dubbo.demo.protobuf.api.GooglePBResponseType)
    }

    // @@protoc_insertion_point(class_scope:org.apache.dubbo.demo.protobuf.api.GooglePBResponseType)
    private static final org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType();
    }

    public static org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GooglePBResponseType>
        PARSER = new com.google.protobuf.AbstractParser<GooglePBResponseType>() {
      public GooglePBResponseType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GooglePBResponseType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GooglePBResponseType> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GooglePBResponseType> getParserForType() {
      return PARSER;
    }

    public org.apache.dubbo.demo.protobuf.api.GooglePb.GooglePBResponseType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016GooglePb.proto\022\"org.apache.dubbo.demo." +
      "protobuf.api\"\"\n\023GooglePBRequestType\022\013\n\003r" +
      "eq\030\001 \001(\t\"(\n\024GooglePBResponseType\022\020\n\010resp" +
      "onse\030\001 \001(\t2\226\001\n\025CDubboGooglePBService\022}\n\010" +
      "sayHello\0227.org.apache.dubbo.demo.protobu" +
      "f.api.GooglePBRequestType\0328.org.apache.d" +
      "ubbo.demo.protobuf.api.GooglePBResponseT" +
      "ypeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBRequestType_descriptor,
        new String[] { "Req", });
    internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_dubbo_demo_protobuf_api_GooglePBResponseType_descriptor,
        new String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
