load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library_internal")

licenses(["notice"])  # Apache 2

api_proto_library_internal(
    name = "client_ssl_auth",
    srcs = ["client_ssl_auth.proto"],
    deps = ["//envoy/api/v2/core:address"],
)
