load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library_internal")

licenses(["notice"])  # Apache 2

api_proto_library_internal(
    name = "header_to_metadata",
    srcs = ["header_to_metadata.proto"],
    deps = [],
)
