name: Check for formatting

on:
  schedule:
    - cron: '*/20 * * * *' # Every 20 minutes

jobs:
  format:
    name: Check if code needs formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
      - name: Check if code aligns with code style
        run: mvn spotless:check
