apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 120Gi
  storageClassName: alicloud-disk-efficiency